// Auto-generated by scripts/sync-frontend-addresses.js
export const DEFAULT_ADDRESSES = {
  token: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9',
  oracle: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
  fund: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
} as const;
